version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 10s
      timeout: 5s

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  kafka-ui:
    image: redpandadata/console:latest
    ports: [ "8088:8080" ]
    environment:
      - KAFKA_BROKERS=kafka:9092

  gateway-websocket:
    build: ./gateway-websocket
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      kafka:
        condition: service_healthy

  user-behaviour-emulator:
    build: ./user-behaviour-emulator
    environment:
      - WS_URL=ws://gateway-websocket:8080/ws/events
      - SEND_INTERVAL_MS=1000
    depends_on:
      gateway-websocket:
        condition: service_healthy

  jobmanager:
    image: flink:1.17.1-scala_2.12
    command: jobmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123
        rest.port: 8081
    ports:
      - "8081:8081"
      - "6123:6123"
    volumes:
      - ./flink-job/build/libs:/jars
    depends_on:
      kafka:
        condition: service_healthy

  taskmanager:
    image: flink:1.17.1-scala_2.12
    command: taskmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123
    volumes:
      - ./flink-job/build/libs:/jars
    depends_on:
      - jobmanager

  flink-job:
    image: flink:1.17.1-scala_2.12
    depends_on:
      jobmanager:
        condition: service_started
    volumes:
      - ./flink-job/build/libs:/jars
    command: >
      bash -c "
        /opt/flink/bin/flink run -m jobmanager:8081 -c com.example.flink.UserBehaviourAnalyticsJob /jars/flink-job.jar
      "

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123
      CLICKHOUSE_DB: default

volumes:
  clickhouse-data:
